### ISSUE TITLE
main.py to use parameters/flags to use either fake or actual AIs

### ISSUE THREAD

**Issue by lpabon** [aipresenter/aipresenter#37]

**Comment by lpabon** [comment]
see https://github.com/lpabon/ghstats/blob/master/ghstats.py#L113-L121

**Comment by lpabon** [comment]
What we want is: `python3 main.py --script=myscript.yml`

We can then also do`python3 main.py --help`

**Comment by immanuelpabon** [comment]
duplicate of #51
